Scripts: git-web give nice error if no git repo

diff --git a/my-scripts/bin/git-web b/my-scripts/bin/git-web
--- a/my-scripts/bin/git-web
+++ b/my-scripts/bin/git-web
@@ -1,5 +1,13 @@
 #! /usr/bin/env bash
 
+SCRIPTNAME=$(basename $0)
+
+git rev-parse --git-dir > /dev/null 2>&1
+if [[ $? != 0 ]]; then
+    echo "${SCRIPTNAME}: couldn't find a git repo"
+    exit 1
+fi
+
 REMOTE_ORIGIN_URL=$(git config --get remote.origin.url)
 
 # https://stackoverflow.com/a/36798723/1107844
@@ -12,7 +20,7 @@ if [[ $REMOTE_ORIGIN_URL =~ "gitlab" ]]; then
 elif [[ $REMOTE_ORIGIN_URL =~ "github" ]]; then
     PREFIX="https://github.com"
 else
-    echo "Couldn't work out site for ${REMOTE_ORIGIN_URL}"
+    echo "${SCRIPTNAME}: Couldn't work out site for ${REMOTE_ORIGIN_URL}"
     exit 1
 fi
 
@@ -41,5 +49,5 @@ if [[ $1 =~ ^(browse|pipe|pipes|commits|url)$ ]]; then
     shift
     $COMMAND "$@"
 else
-    exit 1
+    echo "syntax is: '${SCRIPTNAME} [browse|pipe|pipes|commits|url]'"
 fi
